db_config:
    database_name: str(none=False)
    table_name: str(none=False)
    id_name: str(none=False)
    left_name: str(none=False)
    word_name: str(none=False)
    right_name: str(none=False)
    freq_name: str(none=False)
contextbank_config:
    left_size: int(none=False)
    right_size: int(none=False)
    hide_char: str(none=False)
guesser_config:
    baseurl: any(str(none=False), null())
    guesser: any(str(none=False), null())
    retry_wrong: any(bool(none=False), null())
    top_n: any(int(min=1, none=False), null())
ui_strings:
    title: str(none=False)
    guess: str(none=False)
    give_up: str(none=False)
    next_line: str(none=False)
    new_game: str(none=False)
    new_game_vs_other: str(none=False)
    previous_guesses: str(none=False)
    previous_guesses_other: str(none=False)
    no_guessed_word_specified: str(none=False)
    no_displayed_lines_specified: str(none=False)
    no_action_specified: str(none=False)
    win: str(none=False)
    incorrect_guess: str(none=False)
    no_more_line_for_word: str(none=False)
    error: str(none=False)
    footer: str(none=False)
