database_name: str(required=False, none=False)
table_name: str(required=False, none=False)
id_name: str(required=False, none=False)
left_name: str(required=False, none=False)
word_name: str(required=False, none=False)
right_name: str(required=False, none=False)
ui-strings:
    title: str(required=False, none=False)
    guess: str(required=False, none=False)
    give_up: str(required=False, none=False)
    next_sent: str(required=False, none=False)
    new_game: str(required=False, none=False)
    previous_guesses: str(required=False, none=False)
    no_guessed_word_specified: str(required=False, none=False)
    no_displayed_sentences_specified: str(required=False, none=False)
    no_action_specified: str(required=False, none=False)
    win: str(required=False, none=False)
    incorrect_guess: str(required=False, none=False)
    no_more_sent_for_word: str(required=False, none=False)
    footer: str(required=False, none=False)
