db_config:
    database_name: human_measurement2.db
    table_name: lines
    id_name: id
    left_name: left
    word_name: kwic
    right_name: right
    valid_words_name: valid_words
    construction_type_name: construction_type
contextbank_config:
    left_size: 5000
    right_size: 5000
    hide_char: _
guesser_config:
    baseurl: null
    guesser: null
    similarity: null
    retry_wrong: null
    top_n: null
ui_strings:
    title: Szókitaláló játék
    guess: Tipp
    give_up: Szabad a gazda
    next_line: Még egy sor
    new_game: Új játék
    new_game_vs_other: Új játék a BERT ellen
    previous_guesses: Eddigi tippek
    previous_guesses_other: A BERT eddigi tippjei
    no_guessed_word_specified: Hiányzó paraméter (a tippelt szó) !
    no_displayed_lines_specified: Hiányzó paraméter (a megjelenített sorok azonosítói) !
    no_action_specified: Hiányzó paraméter (a kövekező lépés) !
    win: Eltaláltad! :)
    incorrect_guess: Nem talált! :(
    no_more_line_for_word: Nincs több sor! :(
    other_win: A BERT eltalálta!
    other_gave_up: A BERT feladta!
    other_guess_state_invalid: Nem megfelelő paraméterérték (other_guess_state) !
    error: Hiba történt
    description: Részletek
    ok: Rendben
    footer: <p>Kedves Játékos!<br>Az alábbi nyelvi játék célja annak vizsgálata, hogy hogyan használják az emberek a magyar nyelvet. A játék során olyan értelmes mondatokat fogsz látni, amelyekben egy szót eltakartunk. A feladatod, hogy kitaláld a kitakart szót minél kevesebb mondatból. Tippelhetsz korlátlanul.  Ha éppen nincs ötleted a megoldásra, kérhetsz újabb mondatot. Az egymás alatti _ karakterek ugyanazt a kifejezést rejtik más-más mondatokból vett környezetekkel. Összesen tízszer kérhetsz új mondatot. Ha elfogytak a tippjeid és már új sort sem tudsz kérni, a "Szabad a gazda" gombra kattintva megmutatjuk a megoldást.<br>Ha szeretnél pihenőt tartani, vagy később folytatnád a már elkezdett játékot, mentsd el a linket (URL), és használd újra, amikor szeretnél játszani! Kérjük, csak akkor mentsd el a linket és hagyd abba a játékot, ha sikerült kitalálnod a szót, vagy feladtad a játékot.<br>Jó szórakozást kívánunk! :)</p>
