db_config:
    database_name: webcorpus1_conts.db
    table_name: lines
    id_name: id
    left_name: left
    word_name: word
    right_name: right
    freq_name: freq
contextbank_config:
    left_size: 5
    right_size: 5
    hide_char: X
guesser_config:
    baseurl: http://porthos.elte-dh.hu:5000/
    guesser: bert
    similarity: cbow
    retry_wrong: False
    top_n: 10
ui_strings:
    title: Szókitaláló játék
    guess: Tipp
    give_up: Szabad a gazda
    next_line: Még egy sor
    new_game: Új játék
    new_game_vs_other: Új játék a BERT ellen
    previous_guesses: Eddigi tippek
    previous_guesses_other: A BERT eddigi tippjei
    no_guessed_word_specified: Hiányzó paraméter (a tippelt szó) !
    no_displayed_lines_specified: Hiányzó paraméter (a megjelenített sorok azonosítói) !
    no_action_specified: Hiányzó paraméter (a kövekező lépés) !
    win: Eltaláltad! :)
    incorrect_guess: Nem talált! :(
    no_more_line_for_word: Nincs több sor! :(
    other_win: A BERT eltalálta!
    other_gave_up: A BERT feladta!
    other_guess_state_invalid: Nem megfelelő paraméterérték (other_guess_state) !
    error: Hiba történt
    footer: <p>Találd ki a szót minél kevesebb sorból! Az X karakterek ugyanazt a szót rejtik más-más mondatokból vett kontextusokkal. (Az X karakterek száma megegyezik a kitalálandó szó karaktereinek számával.)</p>
            <br>
            <p>Az oldal alatt futó kód a <em>Nyelvi játék © MorphoLogic, 2000</em> működése alapján készült, független kódbázissal.</p>
            <p>Adatbázis:\ Kornai András et al. – <a href="http://mokk.bme.hu/resources/webcorpus/">Magyar Webkorpusz</a></p>
            <p>A Magyar Webkorpusz felhasználása esetén az alábbi publikációk legalább egyike hivatkozandó:</p>
            <ul>
                <li><a href="https://aclanthology.org/W06-1701/">András Kornai, Péter Halácsy, Viktor Nagy, Csaba Oravecz, Viktor Trón, and Dániel Varga. 2006. Web-based frequency dictionaries for medium density languages. In Proceedings of the 2nd International Workshop on Web as Corpus.</a></li>
                <li><a href="https://aclanthology.org/L04-1320/">Péter Halácsy, András Kornai, László Németh, András Rung, István Szakadát, and Viktor Trón. 2004. Creating Open Language Resources for Hungarian. In Proceedings of the Fourth International Conference on Language Resources and Evaluation (LREC’04), Lisbon, Portugal. European Language Resources Association (ELRA).</a></li>
            </ul>
