db_config:
    database_name: webcorpus1_conts.db
    table_name: lines
    id_name: id
    left_name: left
    word_name: word
    right_name: right
    freq_name: freq
contextbank_config:
    left_size: 5
    right_size: 5
    hide_char: X
guesser_config:
    baseurl: null
    guesser: null
    similarity: null
    retry_wrong: null
    top_n: null
ui_strings:
    title: Szókitaláló játék
    guess: Tipp
    give_up: Szabad a gazda
    next_line: Még egy sor
    new_game: Új játék
    new_game_vs_other: Új játék a BERT ellen
    previous_guesses: Eddigi tippek
    previous_guesses_other: A BERT eddigi tippjei
    no_guessed_word_specified: Hiányzó paraméter (a tippelt szó) !
    no_displayed_lines_specified: Hiányzó paraméter (a megjelenített sorok azonosítói) !
    no_action_specified: Hiányzó paraméter (a kövekező lépés) !
    win: Eltaláltad! :)
    incorrect_guess: Nem talált! :(
    no_more_guess: Nincs több lehetőség találgatni! :(
    no_more_line_for_word: Nincs több sor! :(
    no_more_sent: Nincs több! Köszönjük, hogy végigcsináltad! :)
    other_win: A BERT eltalálta!
    other_gave_up: A BERT feladta!
    other_guess_state_invalid: Nem megfelelő paraméterérték (other_guess_state) !
    error: Hiba történt
    footer: <p>Találd ki a szót! Az X karakterek száma megegyezik a kitalálandó szó karaktereinek számával!</p>
            <br>
            <p>Maximum 10 tippet lehet írni mondatonként!</p>
            <p>Egér nélkül is játszható. A fókusz a beviteli mezőn van, tab-bal lehet a tipp gombra ugrani két tabbal a feladásra utána egy tabbal az új játékra!</p>       
            <p>Összesen 500 mondat van, köszönjük ha rászánod az időt és az összeset végigcsinálod!</p>  
            <p>Ha félbe akarod hagyni két játék között tedd, amikor feladtad vagy kitaláltad, de még nem nyomtál az "Új játék" gombra"!</p>
            <p>Kérünk, mentsd el az URL-t és azzal folytasd, hogy ne kezdődjön újra a teszt!</p>
