database_name: webcorpus_conc.db
table_name: examples
id_name: id
left_name: left
word_name: word
right_name: right
ui-strings:
    title: Szókitaláló játék
    guess: Tipp
    give_up: Szabad a gazda
    next_sent: Még egy mondat
    new_game: Új játék
    previous_guesses: Eddigi tippek
    no_guessed_word_specified: Hiányzó paraméter (a tippelt szó) !
    no_displayed_sentences_specified: Hiányzó paraméter (a megjelenített mondatok azonosítói) !
    no_action_specified: Hiányzó paraméter (a kövekező lépés) !
    win: Eltaláltad! :)
    incorrect_guess: Nem talált! :(
    no_more_sent_for_word: Nincs több mondat! :(
    footer: Találd ki a szót minél kevesebb mondatból! Az X karakterek ugyanazt a szót rejtik más-más modatokból vett kontextusokkal. (Az X karakterek száma megegyezik a kitalálandó szó karaktereinek számával.)
