database_name: prevcons_conc.db
table_name: examples
id_name: id
left_name: left
word_name: word
right_name: right
ui-strings:
    title: Szókitaláló játék "Ági edition"
    guess: Tipp
    give_up: Szabad a gazda
    next_sent: Még egy mondat
    new_game: Új játék
    previous_guesses: Eddigi tippek
    no_guessed_word_specified: Hiányzó paraméter (a tippelt szó) !
    no_displayed_sentences_specified: Hiányzó paraméter (a megjelenített mondatok azonosítói) !
    no_action_specified: Hiányzó paraméter (a kövekező lépés) !
    win: Eltaláltad! :)
    incorrect_guess: Nem talált! :(
    no_more_sent_for_word: Nincs több mondat! :(
    footer: Találd ki az igekötőt minél kevesebb mondatból! Az X karakterek ugyanazt az igekötőt rejtik más-más mondatokból vett kontextusokkal. (Az X karakterek száma megegyezik a kitalálandó igekötő karaktereinek számával.)
            <br><br>
            Adatbázis:\ Kalivoda Ágnes – <a href="https://github.com/kagnes/prevcons">PrevCons</a><br>
            <br>
            <p>A PrevCons felhasználása esetén az alábbi publikációk egyike hivatkozandó:</p>
            <ul>
                <li><a href="https://doi.org/10.34103/ARGUMENTUM/2021/4">Kalivoda Ágnes (2021). Az igekötők produktív kapcsolódási mintái. Argumentum 17. p. 56-82. https://doi.org/10.34103/ARGUMENTUM/2021/4</a></li>
                <li><a href="https://github.com/kagnes/phd_thesis">Kalivoda Ágnes (2021). Igekötős szerkezetek a magyarban. Doktori értekezés. PPKE BTK, Nyelvtudományi Doktori Iskola. Budapest. Megjelenés alatt.</a></li>
            </ul>
