db_config:
    database_name: pl_oscar_2019_dedup_conts.db
    table_name: lines
    id_name: id
    left_name: left
    word_name: word
    right_name: right
    freq_name: freq
contextbank_config:
    left_size: 5
    right_size: 5
    hide_char: X
guesser_config:
    baseurl: null
    guesser: null
    similarity: null
    retry_wrong: null
    top_n: null
ui_strings:
    title: Word guessing game
    guess: Guess
    give_up: Give up
    next_line: Add a line
    new_game: New game
    new_game_vs_other: New game against BERT
    previous_guesses: Previous guesses
    previous_guesses_other: Previous guesses from BERT
    no_guessed_word_specified: Missing parameter (guessed word) !
    no_displayed_lines_specified: Missing parameter (the ids of the displayed lines) !
    no_action_specified: Missing parameter (the next action) !
    win: You guessed it! :)
    incorrect_guess: Incorrect guess! :(
    no_more_line_for_word: No more lines! :(
    other_win: BERT guessed it!
    other_gave_up: BERT gave up!
    other_guess_state_invalid: Incorrect parameter value (other_guess_state) !
    error: An error occurred
    description: Description
    ok: OK
    footer: <p>Guess the word in as few lines as possible! X characters hide the same word with contexts taken from different sentences.<br>(The number of X characters is the same as the number of characters in the word to be guessed.)</p>
            <br>
            <p>The code running below the page is based on the operation of <em>Language game © MorphoLogic, 2000</em>, with an independent codebase.</p>
            <p>Database:\ Ortiz Suárez et al. – <a href="https://oscar-project.github.io/documentation/versions/oscar-2019/">OSCAR 2019 polish deduplicated corpus</a></p>
            <p>When using the underlying corpus, the following publication must be cited:</p>
            <ul>
                <li><a href="https://aclanthology.org/2020.acl-main.156/">Pedro Javier Ortiz Suárez, Laurent Romary, and Benoît Sagot. 2020. A Monolingual Approach to Contextualized Word Embeddings for Mid-Resource Languages. In Proceedings of the 58th Annual Meeting of the Association for Computational Linguistics, pages 1703–1714, Online. Association for Computational Linguistics.</a></li>
            </ul>
